export const FETCH_SESSION = 'FETCH_ACCOUNT_INFO'
export const FETCH_SESSION_SUCCESS = 'FETCH_ACCOUNT_INFO_SUCCESS'
export const FETCH_SESSION_FAILURE = 'FETCH_ACCOUNT_INFO_FAILURE'
export const SET_SESSION_ORGIZATIONS = 'SET_SESSION_ORGIZATIONS'
